name: bling_cc
publish_to: 'none'
description: bling case study.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  auto_route: ^7.2.0
  bloc: ^8.1.0
  country_code_picker: ^3.0.0
  dio: ^5.0.2
  dio_smart_retry: ^5.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  provider: ^6.0.5
  stream_transform: ^2.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.1.4
  flutter_gen_runner: ^5.1.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  http_mock_adapter: ^0.4.4
  injectable_generator: ^2.1.2
  json_serializable: ^6.6.1
  lint: ^2.0.1

flutter_gen:
  output: lib/common/flutter_gen/

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: SF-Pro-Rounded
      fonts:
        - asset: fonts/SF-Pro-Rounded-Thin.ttf
          weight: 100
        - asset: fonts/SF-Pro-Rounded-Extra-Light.ttf
          weight: 200
        - asset: fonts/SF-Pro-Rounded-Light.ttf
          weight: 300
        - asset: fonts/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: fonts/SF-Pro-Rounded-Medium.ttf
          weight: 500
        - asset: fonts/SF-Pro-Rounded-Semi-Bold.ttf
          weight: 600
        - asset: fonts/SF-Pro-Rounded-Bold.ttf
          weight: 700
        - asset: fonts/SF-Pro-Rounded-Extra-Bold.ttf
          weight: 800
        - asset: fonts/SF-Pro-Rounded-Black.ttf
          weight: 900
